### ISSUE TITLE
fail to copy server.xml in assemble-runtime script.

### ISSUE THREAD

**Issue by sachiwo** [WASdev/websphere-liberty-s2i#24]
Hi Team,

I found a bug in assemble-runtime script.

https://github.com/WASdev/websphere-liberty-s2i/blob/bdbf14d366c2fb20b1fb854d749610daee8f39a6/modules/websphere-s2i/artifacts/usr/local/s2i/assemble-runtime#L40

This code is probably wrong.
We think the correct code would look like this

```
cp $OUTPUT_DIR/src/main/liberty/config/server.xml $SERVER_DIR
```

In fact, the variable $LOCAL_SOURCE_DIR is not defined anywhere, so this variable is blank, which caused the Server.xml copy to fail.

May I ask you to check?

**Comment by brenthdaniel** [comment]
Hi, 
  Thanks for the report. This does look like a bug. I'll fix it shortly.
